### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by jondashkyle** [jondashkyle/nanopage#7]
here’s a trip. consider how nanopage referenced `pages` with a nested object. that was removed and now there is a simple regex against the flat `state.content` object. what if we did the same for `files`? in this case, you could have `state.content` which looks like this:

```js
{
  '/': {
    title: 'Index'
   },
  '/example.jpg': {
    name: 'example',
    extension: 'jpg'
  }
}
```

started thinking about this when i implemented the updated `find` utility, which does this and would nicely work with passing filenames:

```js
// updated find utility
if (typeof value.url === 'string') {
    return state.content[resolve(value.url, url)]
}

// example usage
page().find('test.jpg').v()
```

should likely update the `pages` regex to ensure there is no extension. likewise, should update `files` to look more like `pages`, but ensure there is an extension. also, perhaps we could pass an argument into the `pages` and `files` utils which returns a glob of children.

```js
page('/example').pages(true).v()
// returns /example/one, /example/two, /example/two/child, etc…
```

this way we could dynamically add pages to a router without a bunch of rogue files ended up in there:

```js
// choo router example
page('/').pages(true).keys().forEach(href => app.route(href, view(state, emitter.emit))

// want all your files?
page('/').files(true).v()
```

might be getting a little obscure with that router example.

**Comment by jongacnik** [comment]
Top level files is interesting, as is the ability to access recursive children (I had it working like this initially with the regex). So the thinking here is files would be stored with their full path?

```js
{
  '/some/nested/page/file.jpg': {},
  '/another/nested/page/file.jpg': {}
}
```

Being able to easily access every file is cool. Eventually we could maybe even expose some sort of top level `file()` helper, like `page()`:

```js
var myFile = file('/some/nested/page/file.jpg')
```

The router example is funny - is there a reason you would ever register every route like that and not just use `:params`?

**Comment by jondashkyle** [comment]
yeah, stored as their full path. the `file` method is interesting too. yeah, you’d prob never do that router example, but i was trying to think of an instance where you would want more of a `glob` of every page.

**Comment by jondashkyle** [comment]
oh interesting, yeah… I dunno if the performance thing is actually an issue for the scale of projects nanopage is engaging. but yeah—if we were to us a `files` object, we should probably change from using `content` to `pages`.

**Comment by jondashkyle** [comment]
This has been implemented in the `dev` branch: https://github.com/jondashkyle/nanopage/pull/14
